### PR TITLE
Resolve file if wildcard element is used

### LINKED ISSUE #330: Invalid imports in generated d.ts for project with tsconfig path alias defined for any module
### Describe the bug

I have a project, where I have path aliases defined in `tsconfig.json` to simplify usage of any module within src folder:
```
    "paths": {
      "*": ["src/*"],
    },
```
This setting allows to simplify the imports, so that instead of:
`import { Sample } from 'src/components/Sample';` (or even `import { Sample } from '@/components/Sample';`)
we can use:
`import { Sample } from 'components/Sample';`

When I build the app, the app itself works fine (thanks to the `vite-tsconfig-paths`), but all the `d.ts` files for `.ts` files that are inside a subfolder of src, are generated with invalid `import` paths.

The original ts file:
image
The output d.ts file:
image

It was working fine in `vite-plugin-dts@3.6.4`. Any version since then (so starting from v3.7.0) has the issue.
Possibly there is an issue in this commit that was introduced in 3.7.0:
https://github.com/qmhc/vite-plugin-dts/commit/e8827cb6c8be1406e4e3a9a24639b7b54ca20d53

### Reproduction

https://stackblitz.com/edit/vitejs-vite-sg53ed?file=dist%2Ftypes%2Fcomponents%2FSample%2Findex.d.ts

### Steps to reproduce

- create sample app (react based for example), with vite + vite-plugin-dts + vite-tsconfig-paths
- create any subfolder (like "components") inside `src`, and there create any other folder containing some sample component:
```
src
- components
-- Sample
--- Sample.tsx
--- index.ts
```
where `index.ts` is only reexporting the component
```
export * from './Sample';
```
- import the component in App.tsx: `import { Sample } from 'components/Sample';`

- set the project's configuration:

**package.json**
vite related libraries:
```
    "vite": "^5.2.0",
    "vite-plugin-dts": "^3.9.1",
    "vite-tsconfig-paths": "^4.3.2"
```

 **tsconfig.json**
add the following `"paths"`:
```
    "paths": {
      "*": ["src/*"],
    }
```

**vite.config.ts**
```
import * as path from 'path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import dts from 'vite-plugin-dts';
import tsconfigPaths from 'vite-tsconfig-paths';

import * as packageJSON from './package.json';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    dts({
      entryRoot: path.resolve(__dirname, 'src'),
      outDir: path.resolve(__dirname, 'dist', 'types'),
    }),
    tsconfigPaths(),
  ],
  build: {
    rollupOptions: {
      external: Object.keys(packageJSON.dependencies),
    },
  },
});
``` 

- run `vite build` command
- in `dist/types` folder you will find d.ts files with invalid import paths

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13800H
    Memory: 13.18 GB / 31.66 GB
  Binaries:
    Node: 18.20.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react: ^4.2.1 => 4.2.1
    vite: ^5.2.0 => 5.2.11
    vite-plugin-dts: ^3.9.1 => 3.9.1
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by lachieh**
- **test: correct path relative to configured filePath**
- **test: add failing test**
- **fix: add resolution step if alias is wildcard at root. Closes #330**

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -438,6 +438,33 @@ export function parseTsAliases(basePath: string, paths: ts.MapLike<string[]>) {
...
+    '.vue.d.ts'
+  ]
+
+  for (const ext of files) {
+    if (existsSync(path + ext)) {
+      return true
+    }
+  }
+  return false
+}
```
Comment (lachieh) [inline src/utils.ts:466]: Not really sure if this is the best way to do this. This current solution assumes a lot and isn't really configurable though it might be enough at this point. I thought about using the ts program but didn't want to go that deep and I'm not really sure it'd even be useful.

File: tests/transform.spec.ts [hunk 2]
```diff
@@ -216,14 +230,14 @@ describe('transform tests', () => {
...
+      '*': ['tests/__fixtures__/*']
     }
 
-    const aliases = parseTsAliases(resolve(__dirname), tsPaths)
+    const aliases = parseTsAliases(resolve(__dirname, '..'), tsPaths)
 
     const options = (content: string) => ({
       content,
-      filePath: resolve(__dirname, './src/index.ts'),
+      filePath: resolve(__dirname, '../src/index.ts'),
```
Comment (lachieh) [inline tests/transform.spec.ts:240]: aliases were assuming top level was in the `tests` folder resulting in absolute paths being `~/tests/src/...` etc. so going up a directory here fixes this

File: tests/transform.spec.ts [hunk 3]
```diff
@@ -243,12 +257,12 @@ describe('transform tests', () => {
...
-      "import { TestBase } from './utils/test';\n"
+    expect(transformCode(options('import { TestBase } from "resolvePath";')).content).toEqual(
+      "import { TestBase } from '../tests/__fixtures__/resolvePath';\n"
     )
 
-    expect(transformCode(options('import { TestBase } from "test.path";')).content).toEqual(
-      "import { TestBase } from './utils/test.path';\n"
+    expect(transformCode(options('import { TestBase } from "test.resolvePath";')).content).toEqual(
+      "import { TestBase } from '../tests/__fixtures__/test.resolvePath';\n"
     )
```
Comment (lachieh) [inline tests/transform.spec.ts:266]: changing to real file path

File: src/utils.ts (hunk 1 above)
Comment (lachieh) [reply src/utils.ts:466]: @qmhc any thoughts?

Comment (qmhc) [reply src/utils.ts:466]: Well, I'm not sure it's possible to use `ts.resolveModuleName` to implement this feature.

Comment (lachieh) [reply src/utils.ts:466]: Do you think this needs any more work to merge?

Comment (qmhc) [reply src/utils.ts:466]: I think we should add `.mts` and `.cts` extensions, and because we have provided the svelte resolver, we should also consider `.svelte` files.

Comment (lachieh) [reply src/utils.ts]: Ok, that's done!

**Comment by lachieh** [comment]
@qmhc this should be ready to merge now. Thank you!

**Review by qmhc — APPROVED** [review]
